apiVersion: kibana.k8s.elastic.co/v1
kind: Kibana
metadata:
  name: mintk
spec:
  version: 8.7.0
  count: 1

  config:
    #    xpack.fleet.agents.elasticsearch.host: "http://mit-es-http.knx.svc:9200"
    xpack.fleet.agents.elasticsearch.host: "https://mintk-es.kernellix.net"
    #    xpack.fleet.agents.fleet_server.hosts: ["https://fleet-server-agent-http.mit.svc:8220"]
    xpack.fleet.agents.fleet_server.hosts: ["https://mintk-fleet.kernellix.net"]
    monitoring.ui.ccs.enabled: false
    xpack.fleet.packages:
      - name: system
        version: latest
      - name: elastic_agent
        version: latest
      - name: fleet_server
        version: latest
    xpack.fleet.agentPolicies:
      - name: Fleet Server on ECK policy
        id: eck-fleet-server
        is_default_fleet_server: true
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        package_policies:
          - name: fleet_server-1
            id: fleet_server-1
            package:
              name: fleet_server
      - name: Elastic Agent on ECK policy
        id: eck-agent
        namespace: default
        monitoring_enabled:
          - logs
          - metrics
        unenroll_timeout: 900
        is_default: true
        package_policies:
          - name: system-1
            id: system-1
            package:
              name: system

  elasticsearchRef:
    name: mintk
  http:
    service:
      spec:
        type: NodePort
    tls:
      selfSignedCertificate:
        disabled: true
